package model;
// Generated 30/08/2018 20:48:27 by Hibernate Tools 4.3.1



/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int idProduto;
     private String descricao;
     private Float preco;
     private Integer quantidade;
     private Byte disponivel;

    public Produto() {
    }

	
    public Produto(int idProduto) {
        this.idProduto = idProduto;
    }
    public Produto(int idProduto, String descricao, Float preco, Integer quantidade, Byte disponivel) {
       this.idProduto = idProduto;
       this.descricao = descricao;
       this.preco = preco;
       this.quantidade = quantidade;
       this.disponivel = disponivel;
    }
   
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Float getPreco() {
        return this.preco;
    }
    
    public void setPreco(Float preco) {
        this.preco = preco;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Byte getDisponivel() {
        return this.disponivel;
    }
    
    public void setDisponivel(Byte disponivel) {
        this.disponivel = disponivel;
    }




}


